stages:
  - build
  - test
default:
  image: ruby:2.6

build challenge:
  image: maven:3-jdk-8
  stage: build
  tags:
    - maven
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

unit_test:
  image: maven:3-jdk-8
  stage: test
  tags:
    - maven
  script: "mvn clean test"
